config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "base#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, foreign_key: :author_id
  belongs_to :post

  after_save :update_post_counts

  private

  def update_post_counts
    post.increment!(:comment_count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  belongs_to :post

  after_save :update_post_likes_count

  private

  def update_post_likes_count
    post.increment!(:like_count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, foreign_key: :author_id
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { in: 1..250 }
  validates :comment_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :like_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_count

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_post_count
    user.increment!(:post_count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  validates :name, presence: true
  validates :post_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  def index; end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @user = current_user
  end

  def create
    comment = Comment.new(comment_params)
    comment.author_id = current_user.id
    comment.post_id = params[:post_id]

    if comment.save
      redirect_to user_posts_path(params[:user_id])
    else
      redirect_to new_user_post_comment
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = Like.new(like_params)
    if like.save
      redirect_back(fallback_location: root_path)
    else
      puts 'Error'
    end
  end

  def like_params
    params.require(:like).permit(:author_id, :post_id)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.where(author_id: params[:user_id])
    @comments = Comment.all
    @users = User.all
  end

  def show
    @post = Post.find(params[:id])
    @users = User.all
    @comments = Comment.all
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def create
    post = Post.new(post_params)
    post.author_id = current_user.id

    if post.save
      redirect_to user_posts_path(current_user)
    else
      redirect_to new_user_post_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_login_helper.rb
module UserLoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/base/index.html.erb
<form class="login">
  <input type="text" placeholder="Username">
  <input type="password" placeholder="Password">
  <button class="login_btn">
    <%= link_to "Login", users_path %>
  </button>
</form>

app/views/comments/new_comment.html.erb
<div class="form">
  <h1 class="form_header">Leave a comment</h1>
  <%= form_with model: @comment, url: user_post_comments_path do |f| %>
    <div class="text_form">
      <%= f.label :text %>
      <%= f.text_area :text, class: 'text-form'%>
    </div>

    <div class="form-submit">
      <%= f.submit "Add Comment" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<% identifier = @posts.first %>
<% user = User.find(id = identifier.author_id) %>

<div class="card">
  <%= render partial: "shared/user_card", locals: { user: user } %>
</div>

<% @posts.each do |post| %>
  <div class="post">
    <%= render partial: "shared/post_card", locals: { post: post } %>
    <button class="user_btn">
      <%= link_to "Access", user_post_path(user, post) %>
    </button>
    <%= render partial: "shared/like", locals: {user: user, post: post}%>  
  </div>
  
  <div class="comments">
    <% post.recent_five_comments.each do |comment|%>
      <%= render partial: "shared/post_comment", locals: { users: @users, comment: comment} %>
    <% end %>
  </div>
<% end %>

app/views/posts/new_post.html.erb
<div class="form">
  <h1>Add New Post</h1>
  <%= form_with model: @post, url: user_posts_path  do |f| %>
    <div class="form-title">
      <%= f.label :title  %>
      <%= f.text_field :title, class: 'title-form'%>
    </div>

    <div class="text_form">
      <%= f.label :text %>
      <%= f.text_area :text, class: 'text-form'%>
    </div>

    <div class="submit_form">
      <%= f.submit "Add" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<% name = @users.where(id: @post.author_id ) %>
<div class="post_data">
  <div class="post_top">
    <div class="post_author">Post by: <%= name.first.name %></div>
    <div class="post_info">
      <div class="post_comments">Comments: <%= @post.comment_count  %></div>
      <div class="post_likes">Likes: <%= @post.like_count  %></div>
    </div>
  </div>
  <div class="post_title"><%= @post.title  %></div>
  <div class="post_text"><%= @post.text  %></div>
</div>

<div class="comments">
  <% data = @comments.where(post_id: @post.id ) %>
  <% data.each do |comment| %>
    <%= render partial: "shared/postComment", locals: { users: @users, comment: comment} %>
  <% end %>
  <button class=comment_btn>
    <%= link_to "Add comment", new_user_post_comment_path(name.first.id, @post.id) %>
  </button>
</div>
<% end %>

app/views/shared/_like.html.erb
<%= button_to "Like", user_post_likes_path(user, post), params: { like: { author_id: user.id, post_id: post.id}}%>

app/views/shared/_post_card.html.erb
<div class="post_title"><%= post.title %></div>
<div class="post_text"><%= post.text %></div>
<div class="post_info">
  <div class="post_comments">Comments: <%= post.comments_count %></div>
  <div class="post_likes">Likes: <%= post.likes_count %></div>
</div>

app/views/shared/_post_comment.html.erb
<% name = users.where(id: comment.author_id ) %>
<div class="comment">
  <div class="comment_author"><%= name.first.name %>: </div>
  <div class="comment_text"><%= comment.text %></div>
</div>

app/views/shared/_user_card.html.erb
<div class="photo">
  <%= image_tag(user.photo, :alt => "user_photo", :height => "150px", :width => "150px") %>
</div>
<div class="card">
  <div class="user_name"><%= link_to user.name, user %></div>
  <div class="user_posts">Number of posts: <%= user.post_count %></div>
</div>

app/views/users/index.html.erb
<ul>
<h1>Active users</h1>
  <%= @users.each do |user| %>
    <li class="card">
        <%= render partial: "shared/user_card", locals: { user: user } %>
      <button class="btn_user">
        <%= link_to "View", user_path(user) %>
      </button>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="card">
  <div class="img">
    <%= image_tag(@user.photo, width: "130px") %>
  </div>
  <div class="user_card">
    <div class="user_name"><%= @user.name %></div>
    <div class="user_posts">Posts<%= @user.post_count %></div>
  </div>
</div>

<div class="user_bio">
  <div class="user_bio_title">User Bio</div>
  <p class="user_info"><%= @user.bio %></p>
</div>

<%= @count=0 %>

<div class="user_posts">
  <%= @user.recent_posts.each do |post| %>
    <%= @count+=1 %>
    <div class="post_card">
      <div class="post_title">
        <%= post.title %>
      </div>
      <div class="post_body">
        <%= post.text %>
      </div>
      <div class="post_info">
        <div class="comments_count">Comments: <%= post.comment_count %></div>
        <div class="likes_count">Likes: <%= post.like_count %></div>
      </div>
      <br />
    </div>
  <% end %>
</div>

<div class="post_button">
  <button class="post_button">See all posts</button>
</div>